---
- name: Get RDS Admin User
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id '{{ rds_admin_secret_arn }}' \
      --query SecretString --output text | jq -r '.username'
    executable: '/bin/bash'
  changed_when: false
  register: rds_admin_user

- name: Get RDS Admin Password
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id '{{ rds_admin_secret_arn }}' \
      --query SecretString --output text | jq -r '.password'
    executable: '/bin/bash'
  changed_when: false
  register: rds_admin_password

- name: Get RDS Wordpress User
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id 'rds-wp-credentials' \
      --query SecretString --output text | jq -r '.username'
    executable: '/bin/bash'
  changed_when: false
  register: rds_wp_user

- name: Get RDS Wordpress Password
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id 'rds-wp-credentials' \
      --query SecretString --output text | jq -r '.password'
    executable: '/bin/bash'
  changed_when: false
  register: rds_wp_password

- name: Get RDS Grafana User
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id 'rds-grafana-credentials' \
      --query SecretString --output text | jq -r '.username'
    executable: '/bin/bash'
  changed_when: false
  register: rds_grafana_user

- name: Get RDS Grafana Password
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id 'rds-grafana-credentials' \
      --query SecretString --output text | jq -r '.password'
    executable: '/bin/bash'
  changed_when: false
  register: rds_grafana_password

- name: Get Wordpress User
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id 'wp-credentials' \
      --query SecretString --output text | jq -r '.username'
    executable: '/bin/bash'
  changed_when: false
  register: wp_admin_user

- name: Get Wordpress Password
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id 'wp-credentials' \
      --query SecretString --output text | jq -r '.password'
    executable: '/bin/bash'
  changed_when: false
  register: wp_admin_password

- name: Get Stormforge User
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id 'stormforge-credentials' \
      --query SecretString --output text | jq -r '.clientID'
    executable: '/bin/bash'
  changed_when: false
  register: stormforge_user

- name: Get Stormforge Password
  become: false
  ansible.builtin.shell:
    cmd: |
      set -o pipefail && \
      aws secretsmanager get-secret-value \
      --secret-id 'stormforge-credentials' \
      --query SecretString --output text | jq -r '.clientSecret'
    executable: '/bin/bash'
  changed_when: false
  register: stormforge_password
