---
- name: Setup kubectl with eksctl
  ansible.builtin.command: 'eksctl utils write-kubeconfig --cluster={{ cluster_name }} --region={{ region }}'
  changed_when: false

- name: Create wordpress namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ wp_namespace }}'

- name: Create monitoring namespace
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ monitoring_namespace }}'

- name: Create StorageClass for EBS CSI Driver
  kubernetes.core.k8s:
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: '{{ ebs_csi_storage_class }}'
      provisioner: ebs.csi.aws.com
      volumeBindingMode: WaitForFirstConsumer

- name: Create StorageClass for EFS CSI Driver
  kubernetes.core.k8s:
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: '{{ efs_csi_storage_class }}'
      provisioner: efs.csi.aws.com
      parameters:
        provisioningMode: 'efs-ap'
        fileSystemId: '{{ efs_id }}'
        directoryPerms: '700'
        gidRangeStart: '1000'
        gidRangeEnd: '2000'
        basePath: '/wordpress'
