---
- name: Get Grafana user
  ansible.builtin.shell:
    cmd: 'set -o pipefail && kubectl get secret grafana-credentials -n {{ monitoring_namespace }} -o jsonpath="{.data.admin-user}" | base64 --decode ; echo'
    executable: '/bin/bash'
  changed_when: false
  register: grafana_user_output

- name: Get Grafana password
  ansible.builtin.shell:
    cmd: 'set -o pipefail && kubectl get secret grafana-credentials -n {{ monitoring_namespace }} -o jsonpath="{.data.admin-password}" | base64 --decode ; echo'
    executable: '/bin/bash'
  changed_when: false
  register: grafana_password_output

- name: Get Kubernetes dashboard token
  ansible.builtin.shell:
    cmd: 'kubectl -n {{ k8s_dashboard_namespace }} create token {{ k8s_dashboard_sa }} --duration 120m; echo'
  changed_when: false
  register: k8s_dashboard_token

- name: Ansible Password
  ansible.builtin.debug:
    msg:
      - '--- Wordpress ---'
      - 'User: {{ wp_admin_user.stdout }}'
      - 'Password: {{ wp_admin_password.stdout }}'
      - '--- Grafana ---'
      - 'User: {{ grafana_user_output.stdout }}'
      - 'Password: {{ grafana_password_output.stdout }}'
      - '--- Kubernetes Dashboard ---'
      - 'Token: {{ k8s_dashboard_token.stdout }}'
