---
- name: Setup bastion
  hosts: all
  remote_user: ubuntu
  become_user: root
  become: false
  become_method: ansible.builtin.sudo
  vars_files:
    - vars/endpoints.yaml
    - vars/general.yaml
  tasks:
    - name: Install Dependencies
      ansible.builtin.include_tasks: tasks/01_dependencies.yaml
    - name: Get credentials from Secret Manager
      ansible.builtin.include_tasks: tasks/02_credentials.yaml
    - name: Configure EKS
      ansible.builtin.include_tasks: tasks/03_eks.yaml
    - name: Install Metrics Server
      ansible.builtin.include_tasks: tasks/metrics_server.yaml
    - name: Install and configure Karpenter
      ansible.builtin.include_tasks: tasks/karpenter.yaml
    - name: Install Storm forge
      ansible.builtin.include_tasks: tasks/storm_forge.yaml
    - name: Install ALB CRDs
      ansible.builtin.include_tasks: tasks/crds.yaml
    - name: Install Controllers
      ansible.builtin.include_tasks: tasks/controllers.yaml
    - name: Install Kubernetes Dashboard
      ansible.builtin.include_tasks: tasks/kubernetes_dashboard.yaml
    - name: Install Prometheus Stack
      ansible.builtin.include_tasks: tasks/prometheus_stack.yaml
    - name: Install Wordpress
      ansible.builtin.include_tasks: tasks/wordpress.yaml
    - name: Configure Grafana RDS, Datasources and Dashboards
      ansible.builtin.include_tasks: tasks/grafana_config.yaml
    - name: Install Kubecost
      ansible.builtin.include_tasks: tasks/kubecost.yaml
    - name: Install Metricbeat
      ansible.builtin.include_tasks: tasks/metricbeat.yaml
    - name: Install Kubernetes Operational View
      ansible.builtin.include_tasks: tasks/kube_ops_view.yaml
    - name: Output Credentials to login
      ansible.builtin.include_tasks: tasks/output_credentials.yaml
